services:
    database:
        image: postgres:16-alpine
        container_name: smart-inventory-postgres
        environment:
            POSTGRES_DB: SmartInventoryDb
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: mypassword
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data

volumes:
    postgres_data: